name: "Heroku Awake"
description: "Keep a free Heroku dyno awake"
author: "Arga Ghulam Ahmad"
branding:
  icon: "sun"
  color: "yellow"
inputs:
  URL:
    required: true
    description: "The URL of the Heroku web dyno"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.URL }}
