name: Heroku Awake

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "*/30 0-14 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: argaghulamahmad/awake-heroku-apps@master
        with:
          URL: ${{ secrets.IG_TOOLS }}
      - uses: argaghulamahmad/awake-heroku-apps@master
        with:
          URL: ${{ secrets.LI_TOOLS }}
      - uses: argaghulamahmad/awake-heroku-apps@master
        with:
          URL: ${{ secrets.SELF_DEV_TOOLS }}
