name: Heroku Awake

on:
  schedule:
    - cron: "*/30 6-21 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: mikeesto/heroku-awake@1.0.0
        with:
          URL: ${{ secrets.IG_TOOLS }}
      - uses: mikeesto/heroku-awake@1.0.0
        with:
          URL: ${{ secrets.LI_TOOLS }}
      - uses: mikeesto/heroku-awake@1.0.0
        with:
          URL: ${{ secrets.SELF_DEV_TOOLS }}
